apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "verizon-router-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "verizon-router-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "verizon-router-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "verizon-router-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "verizon-router-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROUTER_BASE_URL
              value: {{ .Values.router.baseUrl | quote }}
            - name: ROUTER_USERNAME
              value: {{ .Values.router.username | quote }}
            {{- if .Values.router.existingSecret }}
            - name: ROUTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.router.existingSecret }}
                  key: {{ .Values.router.existingSecretPasswordKey | default "password" }}
            {{- else if .Values.router.password }}
            - name: ROUTER_PASSWORD
              value: {{ .Values.router.password | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
